reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, except: [:index, :destroy]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

reddit-clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :username, :password_digest, :session_token, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }
    attr_reader :password
    after_initialize :ensure_session_token

    has_many :moderated_subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

    has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post

    has_many :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user && user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save
        self.session_token
    end

    private
    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end
end

reddit-clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            sign_in(@user)
            flash[:success] = "New User created!"
            redirect_to subs_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end
    
    def edit
        @user = User.find(params[:id])
        render :edit
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            redirect_to user_url(@user.id)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit-clone/app/views/users/edit.html.erb
<h2>Edit Account</h2>

<form action="<%= user_url(@user) %>" method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="patch">
    <label>
        Username
        <input type="text" name="user[username]" value="<%= @user.username%>">
    </label>
    
    <label>
        Password
        <input type="password" name="user[password]" value="<%= @user.password%>">
    </label>

    <input type="submit" value="Edit Account">
</form>

reddit-clone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
        Username
        <input type="text" name="user[username]">
    </label>
    
    <label>
        Password
        <input type="text" name="user[password]">
    </label>

    <input type="submit" value="Create Account">
</form>

reddit-clone/app/views/users/show.html.erb
<h2>
    <%= @user.username %>'s Account
</h2>

<a href="<%= edit_user_url(@user) %>">Edit Profile</a>