reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, except: [:index, :destroy]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

reddit-clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
    validates :description, :moderator_id, presence: true
    validates :title, uniqueness: true, presence: true
    
    belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

    # has_many :post_subs
    has_many :post_subs, inverse_of: :post, dependent: :destroy

    has_many :posts,
    through: :post_subs,
    source: :post

end

reddit-clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_signed_in!
    before_action :is_moderator!, only: [:update, :edit]

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save
            flash[:success] = "Sub succesfully created"
            redirect_to sub_url(@sub.id)
        else
            flash.now[:errors] = 
            @sub.errors.full_messages
            render :new
        end
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def index
        @subs = Sub.all
        render :index
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update_attributes(sub_params)
            flash[:success] = "Updated, way to go!"
            redirect_to sub_url(@sub.id)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private
    def is_moderator!
        @sub = Sub.find(params[:id])
        if current_user.id != @sub.moderator_id
            flash.now[:errors] = "Not the moderator error!"
            redirect_to sub_url(@sub.id)
        end
    end
    
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

reddit-clone/app/views/subs/edit.html.erb
<h2>Edit a Sub</h2>

<form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="patch">
    <label>
        Title: <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <label>
        Description: <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>
    <input type="submit" value="Edit Sub">
</form>

reddit-clone/app/views/subs/index.html.erb
<h2>All the Subs!</h2>

<% @subs.each do |sub| %>
    <ul>
        <li>
            <a href="<%= sub_url(@sub.id) %>">
                <%= sub.title%>
            </a>
            <p>
                <%= sub.description %>
            </p>
        </li>
    </ul>
<% end %>

<a href="<%=  new_sub_url %>">Create a new Sub</a>

reddit-clone/app/views/subs/new.html.erb
<h2>Create a new Sub</h2>

<form action="<%= subs_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
        Title: <input type="text" name="sub[title]">
    </label>
    <label>
        Description: <input type="text" name="sub[description]">
    </label>
    <input type="submit" value="Create Sub">
</form>

reddit-clone/app/views/subs/show.html.erb
<h2>
<%= @sub.title %>
<%= @sub.description %>
</h2>

<ul>
<% @sub.posts.each do |post|  %>
    <li>
        <a href="<%= post_url(post) %>">
            <%= post.title %>
        </a>
    </li>
<% end %>
</ul>

<a href="<%= new_post_url %>">Create a post</a>
<% if current_user == @sub.moderator_id %>
    <a href="<%= edit_sub_url(@sub) %>">Edit this sub</a>
<% end %>