reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, except: [:index, :destroy]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

reddit-clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
    validates :title, presence: true

    # has_many :post_subs,
    # primary_key: :id,
    # foreign_key: :post_id,
    # class_name: :PostSub

    has_many :post_subs, inverse_of: :post, dependent: :destroy

    has_many :subs, 
    through: :post_subs,
    source: :sub

    belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

    has_many :comments
 end

reddit-clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_signed_in!, except: [:show]
    before_action :is_author!, only: [:edit, :update]
    
    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        if @post.save
            flash[:success] = 'Post created!'
            redirect_to post_url(@post.id)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end
    
    def show
        @post = Post.find(params[:id])
        render :show
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to post_url(@post.id)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to sub_url(@post.sub_id)
    end

    private
    def post_params
        params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end

    def is_author!
        if current_user.id != @post.author_id
            flash[:errors] = "You cannot edit a post you didn't create."
            redirect_to post_url(@post.id)
        end
    end
end

reddit-clone/app/views/posts/edit.html.erb
<h2>Edit the post</h2>

<form action="<%= post_url(@post.id) %>" method="POST">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="PATCH">

    <label>
        Title
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>

    <label>
        URL
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>

    <label>
        Content
        <input type="text" name="post[content]" value="<%= @post.content %>">
    </label>

    <h4>Subs</h4>
    <br>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
        <label> 
            <input 
                type="checkbox" 
                name="post[sub_ids][]" 
                value="<%= sub.id %>"
                <%= "checked" if @post.sub_ids.include?(sub.id) %> >
            <%= sub.title %>
        </label>
        <br>
    <% end %>

    <input type="submit" value="Edit Post">
</form>

reddit-clone/app/views/posts/new.html.erb
<h2>Create a new post</h2>

<form action="<%= posts_url %>" method="POST">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>
        Title
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>

    <label>
        URL
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>

    <label>
        Content
        <input type="text" name="post[content]" value="<%= @post.content %>">
    </label>

    <h4>Subs</h4>
    <br>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
        <label> 
            <input 
                type="checkbox" 
                name="post[sub_ids][]" 
                value="<%= sub.id %>"
                <%= "checked" if @post.sub_ids.include?(sub.id) %> >

                <%= sub.title %>

        </label>
        <br>
    <% end %>
            
    <input type="submit" value="Create Post">
</form>

reddit-clone/app/views/posts/show.html.erb
<h2>Post Show Page</h2>
<p>
<%= @post.title %>
</p>
<p>
<%= @post.url if @post.url %>
</p>
<p>
<%= @post.content if @post.content %>
</p>

<ul>
    <% @post.subs.each do |sub| %>
        <li>
            <a href="<%= sub_url(sub.id) %>">
                <%= sub.title %>
            </a>
            
        </li>
    <% end %>
</ul>

<a href="<%= new_post_comment_url(@post.id) %>">Comment on this post</a>
<br>
<h3>Top-level comments for this post:</h3>
<% @post.comments.each do |comment| %>
    <a href="<%= comment_url(comment.id) %>">
        <%= comment.content %>
    </a>
<% end %>