reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, except: [:index, :destroy]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

reddit-clone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint           not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord
    validates :content, presence: true

    belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User
    
    belongs_to :post

    belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

    has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

end

reddit-clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_signed_in!
    
    def new
        @comment = Comment.new
        render :new
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.author_id = current_user.id
        if @comment.save
            flash[:success] = "Comment created"
            redirect_to post_url(@comment.post_id)
        else
            flash.now[:errors] = @comment.errors.full_messages
            render :new
        end
    end

    def show
        @parent_comment = Comment.find(params[:id])
        @child_comment = @parent_comment.child_comments.new
        render :show
    end

    private
    def comment_params
        params.require(:comment).permit(:content, :post_id)
    end
end

reddit-clone/app/views/comments/new.html.erb
<h2>Add a comment</h2>

<form action="<%= comments_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="comment[post_id]" value="<%= params[:post_id]%>">

    <label>
        Content
        <input type="text" name="comment[content]" value="<%= @comment.content %>">
    </label>
    <input type="submit" value="Add comment">
</form>

reddit-clone/app/views/comments/show.html.erb
<h3>Comment Page</h3>

<h4>Original comment:</h4>
<p><%= @parent_comment.content %></p>

<h4>Add your reply:</h4>
<form action="<%= comments_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="comment[post_id]" value="<%= @parent_comment.post_id %>">
    Content: <input type="text" name="comment[content]" value="<%= @child_comment.content %>">
    <input type="submit" value="Create Nested Comment">
</form>
    